pins/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.homepage, name = 'home'),
    path('create/', views.createpin, name = 'create'),
    path('<int:pin_id>/edit/', views.editpin, name = 'edit'),
    path('<int:pin_id>/delete/', views.deletepin, name = 'delete'),
    path('profile/', views.profile, name = 'profile'),
    path('search/', views.search, name = 'search'),
    path('register/', views.register, name = 'register'),
]

pinterest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pins.urls')),
    path('reload/', include('django_browser_reload.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] +static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

pins/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Pinterest(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    text = models.CharField(max_length = 20)
    photo = models.ImageField(upload_to = 'photos/')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.user.username

pins/forms.py
from django import forms 
from .models import Pinterest
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class PinterestForm(forms.ModelForm):
    class Meta:
        model = Pinterest
        fields = ['photo', 'text']

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

pins/views.py
from django.shortcuts import render
from .forms import PinterestForm, UserRegistrationForm
from .models import Pinterest
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login

# Create your views here.
def homepage(request):
    query = request.GET.get('q')
    pins = Pinterest.objects.all()

    if query:
        pins = pins.filter(text__icontains = query)

    return render(request, 'home.html', {'pins':pins})

@login_required
def createpin(request):
    if request.method == "POST":
        form = PinterestForm(request.POST, request.FILES)
        if form.is_valid():
            pin = form.save(commit=False)
            pin.user = request.user
            pin.save()
            return redirect('home')
    else:
        form = PinterestForm()
    return render(request, 'create.html', {'form':form})
    
@login_required
def editpin(request, pin_id):
    pin = get_object_or_404(Pinterest, pk = pin_id)
    if request.method == "POST":
        form = PinterestForm(request.POST, request.FILES, instance = pin)
        if form.is_valid():
            pin = form.save(commit=False)
            pin.user = request.user
            pin.save()
            return redirect('home')
    else:
        form = PinterestForm()
    return render(request, 'create.html', {'form':form})

@login_required
def deletepin(request, pin_id):
    pin = get_object_or_404(Pinterest, pk = pin_id, user = request.user)
    if request.method == "POST":
        pin.delete()
        return redirect('home')
    return render(request, 'delete.html', {'pin':pin})

def register(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid:
            user = form.save(commit = False)
            user.set_password(form.cleaned_data['password1'])
            user.save()
            return redirect('home')

    else:
        form = UserRegistrationForm()

    return render(request, 'registration/register.html', {'form':form})

@login_required
def profile(request):
    query = request.GET.get('q')
    user = request.user
    pins = Pinterest.objects.filter(user = user)

    if query:
        pins = pins.filter(text__icontains = query)

    return render(request, 'profile.html', {'user': user, 'pins':pins})

def search(request):
    query = request.GET.get('q', '')
    pins = Pinterest.objects.none()

    if query:
        pins = Pinterest.objects.filter(text__icontains = query)
    
    return render(request, 'search.html', {'query':query, 'pins':pins})

pins/templates/create.html
{% extends "layout.html" %}

{% block content %}
    <h1>Welcome!</h1>
    <h2>
        {% if form.instance.pk %} Edit Pin {% else %} Create Pin {% endif %}

        <form method="post" enctype="multipart/form-data" class="form mt-4">
            {% csrf_token %}

            {{ form.text.label_tag }}
            {{ form.text }}
            <label for="id_photo" class="upload-label">Upload Photo</label>
            {{ form.photo }}

            <button class="btn btn-success">Submit</button>
            <a href="{% url 'home' %}" class="btn btn-warning">Back to home page</a>
        </form>
    </h2>

    <style>
        .form input[type="text"],
        .form textarea {
            width: 100%;
            border: none;
            border-bottom: 2px solid #ccc;
            padding: 8px 0;
            outline: none;
            resize: none;
            margin-bottom: 20px;
        }

        .form input[type="text"]:focus,
        .form textarea:focus {
            border-bottom-color: #4F46E5;
        }

        .form input[type="file"] {
            display: none;
        }

        .upload-label {
            display: inline-block;
            padding: 10px 16px;
            background: #4F46E5;
            color: white;
            border-radius: 8px;
            cursor: pointer;
            font-size: 14px;
            margin-bottom: 20px;
        }
    </style>

{% endblock %}

pins/templates/delete.html
{% extends "layout.html" %}

{% block content %}
<h1>Are you sure that you want to delete the pin?</h1>

<form method="post">
    {% csrf_token %}
    <button class="btn btn-danger">Delete</button>
    <a class="btn btn-success" href="{% url 'home' %}">cancel</a>
</form>
{% endblock %}

pins/templates/home.html
{% extends "layout.html" %}

{% block content %}

<div class="container mt-3">
  <form method="GET" class="d-flex mb-3">
    <input 
      type="text" 
      name="q" 
      class="form-control me-2"
      placeholder="Search pins..."
      value="{{ request.GET.q }}"
    >
    <button class="btn btn-dark" type="submit">
      <i class="bi bi-search-heart"></i>
    </button>
  </form>
</div>


<div class="container mt-3">
  <div class="masonry">
    {% for pin in pins %}
      <div class="masonry-item">
        <div class="card">
          <img src="{{pin.photo.url}}" class="card-img-top" alt="">
          <div class="card-body d-flex justify-content-between align-items-start">
            <p class="card-text"> {{pin.text}}</p>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>

<style>
  .masonry {
    column-count: 2;
    column-gap: 12px;
  }

  @media (min-width: 768px) {
    .masonry {
      column-count: 3;
    }
  }

  @media (min-width: 992px) {
    .masonry {
      column-count: 4;
    }
  }

  .masonry-item {
    break-inside: avoid;
    margin-bottom: 12px;
  }

  body {
  padding-bottom: 80px;
  }

</style>


{% endblock %}

pins/templates/profile.html
{% extends "layout.html" %}

{% block content %}

<div class="container m-3">
  <form method="GET" class="d-flex">
    <input 
      type="text" 
      name="q" 
      class="form-control me-2"
      placeholder="Search pins..."
      value="{{ request.GET.q }}"
    >
    <button class="btn btn-dark me-2" type="submit">
      <i class="bi bi-search-heart"></i>
    </button>

    <form action="{% url 'logout' %}" method="post">
      <button class="btn btn-danger " type="submit">Logout</button>
    </form>

  </form>
</div>

<h1> {{user.username}} </h1>
<p> {{user.email}} </p>

<div class="container mt-4">
  <div class="masonry">
    {% for pin in pins %}
      <div class="masonry-item">
        <div class="card">
          <img src="{{pin.photo.url}}" class="card-img-top" alt="">
          <div class="card-body d-flex justify-content-between align-items-start">
            <p class="card-text"> {{pin.text}}</p>

            {% if request.user == pin.user %}
            <div class="dropdown">
              <button class="btn btn-sm" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="bi bi-three-dots-vertical"></i>
              </button>

              <ul class="dropdown-menu dropdown-menu-end">
                <li><a class="dropdown-item" href="{% url 'edit' pin.id %}">Edit</a></li>
                <li><a class="dropdown-item text-danger" href="{% url 'delete' pin.id %}">Delete</a></li>
              </ul>

            </div>
            {% endif %}
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>

<style>
  body {
  padding-bottom: 70px;
  }

  .masonry {
    column-count: 2;
    column-gap: 12px;
  }

  @media (min-width: 768px) {
    .masonry {
      column-count: 3;
    }
  }

  @media (min-width: 992px) {
    .masonry {
      column-count: 4;
    }
  }

  .masonry-item {
    break-inside: avoid;
    margin-bottom: 12px;
  }
</style>

{% endblock %}

pins/templates/search.html
{% extends "layout.html" %}

{% block content %}

<div class="container mt-3">

  <form method="GET" class="d-flex mb-3">
    <input 
      type="text" 
      name="q" 
      class="form-control me-2"
      placeholder="Search pins..."
      value="{{ request.GET.q }}"
    >
    <button class="btn btn-dark" type="submit">
      <i class="bi bi-search-heart"></i>
    </button>
  </form>

    {% if not query %}
        <h3 class="text-center mt-4 text-muted">Looking for a specific pin?</h3>
  
    {% elif pins|length == 0 %}
        <h3 class="text-center mt-4 text-muted">
            No results for "{{ query }}"
        </h3>

    {% else %}
        <h4 class="mb-3">Results for "{{ query }}"</h4>

        <div class="container mt-3">
            <div class="masonry">
                {% for pin in pins %}
                    <div class="masonry-item">
                        <div class="card">
                            <img src="{{pin.photo.url}}" class="card-img-top" alt="">
                            <div class="card-body d-flex justify-content-between align-items-start">
                            <p class="card-text"> {{pin.text}}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

    {% endif %}

</div>

<style>
  .masonry {
    column-count: 2;
    column-gap: 12px;
  }

  @media (min-width: 768px) {
    .masonry {
      column-count: 3;
    }
  }

  @media (min-width: 992px) {
    .masonry {
      column-count: 4;
    }
  }

  .masonry-item {
    break-inside: avoid;
    margin-bottom: 12px;
  }

  body {
  padding-bottom: 80px;
  }
  
</style>


{% endblock %}

templates/layout.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        Pinterest
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    {% tailwind_css %}
</head>
<body class="bg-red-300!">

    <div class="fixed-bottom">
    <nav class="navbar navbar-expand bg-red-400">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
        <i class="bi bi-pinterest"></i>
    </a>
          <ul class="navbar-nav w-100 justify-content-around">
        
            <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home' %}">
            <i class="bi bi-house-heart-fill text-black"></i>
        </a>
        </li>

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href=" {% url 'create' %} ">
            <i class="bi bi-plus text-black"></i>
        </a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'search' %}">
            <i class="bi bi-search-heart text-black"></i>
        </a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href=" {% url 'profile' %} ">
            <i class="bi bi-person text-black"></i>
          </a>
        </li>

      </ul>
  </div>
</nav>
</div>

    <div class="container">
    {% block content %}{% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
</body>
</html>

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Django Tailwind</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% tailwind_css %}
</head>

<body class="bg-gray-50 text-black font-serif leading-normal tracking-normal">
<div class="container mx-auto">
    <section class="flex items-center justify-center h-screen">
        <h1 class="text-5xl">Django + Tailwind = ❤️</h1>
    </section>
</div>
</body>
</html>